[package]
name = "markdown_notes"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
gpui.workspace = true
designsystem.workspace = true
components.workspace = true
platform.workspace = true
