[package]
name = "example_plot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "ttf"] }
thiserror = "1"
